package com.jpacourse.persistence.enums;

public enum Specialization {
	CARDIOLOGY,
	NEUROLOGY,
	PEDIATRICS,
	ORTHOPEDICS,
	DERMATOLOGY,
	OPHTHALMOLOGY,
	GYNECOLOGY,
	ONCOLOGY,
	PSYCHIATRY,
	RADIOLOGY
}